#!/usr/bin/env python3
"""
embed_ui.py — сжимает ui/index.html (gzip -9) и генерирует C-заголовок
с байтовым массивом для встраивания в бинарник microspool.

Без внешних зависимостей (только stdlib). Вызывается из Makefile перед
сборкой native/arm/release целей.

Использование:
    python3 tools/embed_ui.py ui/index.html build/ui_gz.h
"""
import gzip
import os
import sys

BYTES_PER_LINE = 20


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_ui.py <input.html> <output.h>", file=sys.stderr)
        return 1

    src_path, dst_path = sys.argv[1], sys.argv[2]

    with open(src_path, "rb") as f:
        html = f.read()

    # mtime=0 — детерминированный вывод (одинаковые байты при пересборке
    # из тех же исходников, что удобно для кэша сборки и дифов).
    compressed = gzip.compress(html, compresslevel=9, mtime=0)

    out_dir = os.path.dirname(dst_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    lines = []
    lines.append("/* Auto-generated by tools/embed_ui.py from %s -- do not edit. */"
                  % os.path.basename(src_path))
    lines.append("static const unsigned char UI_INDEX_GZ[] = {")
    for i in range(0, len(compressed), BYTES_PER_LINE):
        chunk = compressed[i:i + BYTES_PER_LINE]
        lines.append(",".join(str(b) for b in chunk) + ",")
    lines.append("};")
    lines.append("static const unsigned int UI_INDEX_GZ_LEN = %uu;" % len(compressed))
    lines.append("")

    with open(dst_path, "w", encoding="ascii") as f:
        f.write("\n".join(lines))

    print("embed_ui.py: %s (%d bytes) -> %s (gzip %d bytes)"
          % (src_path, len(html), dst_path, len(compressed)), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
